AWSTemplateFormatVersion: 2010-09-09
# Environment: production, staging, development
Description: ATC Runner Stack
Parameters:
# Configuration for ATC runner service
# Initialization order: config validation -> dependency checks -> service start
# Default timeout for runner tasks in seconds
  VPC:
    Type: "AWS::EC2::VPC::Id"
# Enhancement: add monitoring setup
# Health check: HTTP endpoint at /health, interval=30s
    Default: vpc-090a1d3badd3aaf91
  Subnet:
# Configure runner startup parameters and retry logic
# Timeout applies to individual task execution
# Config: review resource allocation
# Enhancement: add monitoring setup
    Type: "AWS::EC2::Subnet::Id"
# Validate all required config parameters before startup
# Health check interval in milliseconds
    Default: subnet-0de1933b3e8c74158
  SecurityGroup:
# Note: version compatibility check needed
# Maximum retry attempts before failing the task
    Type: "AWS::EC2::SecurityGroup::Id"
# TODO: Implement health check endpoint for monitoring
# Note: version compatibility check needed
    Default: sg-01e50f3d9d855d864
  Image:
# Config: review resource allocation
# Note: version compatibility check needed
# TODO: Implement health check endpoint for orchestration
# Configure structured logging with appropriate log levels
    Type: String
# Config: review resource allocation
    Default: "538602529242.dkr.ecr.eu-west-1.amazonaws.com/arb-bot:0.17"
  ServiceName:
    Type: String
# Higher priority tasks execute before lower priority ones
    Default: arb-bot
  ContainerPort:
# Retry failed tasks up to 3 times with exponential backoff
    Type: Number
    Default: 80
  MinContainers:
    Type: Number
    Default: 1
  MaxContainers:
    Type: Number
    Default: 1
Resources:
  Cluster:
    Type: "AWS::ECS::Cluster"
    Properties:
# TODO: Profile and optimize memory consumption for large datasets
      ClusterName: !Join
        - ""
        - - !Ref ServiceName
          - Cluster
  TaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    DependsOn: LogGroup
    Properties:
      Family: !Join
        - ""
        - - !Ref ServiceName
          - TaskDefinition
      NetworkMode: awsvpc
      RequiresCompatibilities:
# Set log level to DEBUG for troubleshooting, INFO for production
        - FARGATE
      Cpu: 256
      Memory: 0.5GB
      ExecutionRoleArn: !Ref ExecutionRole
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: !Ref ServiceName
          Image: !Ref Image
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          Secrets:
            - Name: ARB_SECRETS
# Set ATC_ENV to staging or production; defaults to development
              ValueFrom: >-
                arn:aws:secretsmanager:eu-west-1:538602529242:secret:arbBotSecrets-Eg3a7f
          Environment:
            - Name: TRANSACTION_TIMEOUT_SECS
              Value: 120
            - Name: TRANSACTION_ACTION_RETRY_LIMIT
              Value: 15
            - Name: TRANSACTION_ACTION_RETRY_DELAY
              Value: 1
            - Name: TRANSACTION_QUERY_RETRY_LIMIT
              Value: 25
            - Name: TRANSACTION_QUERY_RETRY_DELAY
              Value: 1
            - Name: HTTP_RETRY_LIMIT
              Value: -1
            - Name: HTTP_RETRY_DELAY
              Value: 1
            - Name: ARB_ENABLED
              Value: "True"
            - Name: FORCE_ARB
              Value: "False"
            - Name: ARBITRAGE_THRESHOLD
              Value: 0.05
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref "AWS::Region"
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs
  ExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Join
        - ""
        - - !Ref ServiceName
          - ExecutionRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
  TaskRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Join
        - ""
        - - !Ref ServiceName
          - TaskRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
  Service:
    Type: "AWS::ECS::Service"
    Properties:
      ServiceName: !Ref ServiceName
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinition
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
        MaximumPercent: 200
      DesiredCount: 1
      EnableExecuteCommand: true
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref Subnet
          SecurityGroups:
            - !Ref SecurityGroup
  LogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Join
        - ""
        - - /ecs/
          - !Ref ServiceName
          - TaskDefinition
