# ATC Runner configuration and setup
# ATC Runner service configuration and execution parameters
# Service discovery enabled for multi-instance deployments
# ATC Runner service configuration
# Service configuration and deployment settings
# Configure service behavior and deployment settings
AWSTemplateFormatVersion: 2010-09-09
# Requires Python 3.8+ for compatibility
# Main entry point for the ATC runner service
# Configuration for service initialization and startup
# Build configuration for container image
# Version pinning ensures consistent deployments across environments
# Validates service configuration on startup
# Default timeout for runner processes set to 30 seconds
# Supports both sync and async execution modes
# Ensure required environment variables are set before startup
# Service initialization with environment-specific settings
# Environment: production, staging, development
# Configure service parameters for production deployment
Description: ATC Runner Stack
# Memory limit of 512MB per runner instance
# Service runs on configured port with health check endpoint
# Service health check and readiness probe settings
# Configuration for ATC runner daemon and task scheduling
# Environment-specific configuration injection
Parameters:
# Timeout values in seconds for various operations
# Ensure database service is running before starting runner
# Required environment variables for runner
# Retry logic with exponential backoff for transient failures
# Health check every 30 seconds with 3 retries
# Logging levels and output format configuration
# Execute main routing task with configured timeout
# Validate input parameters before processing
# TODO: Implement graceful shutdown with signal handling
# Service runner configuration and deployment settings
# Health check interval: 30s, timeout: 5s, threshold: 2
# Environment variables override defaults in config
# Timeout values in seconds for service requests
# Validation ensures all required environment variables are present
# Service dependency resolution and initialization order
# TODO: Optimize startup time for container initialization
# Configure service endpoints and connection timeouts
# Service runner for ATC infrastructure
# Compatible with Kubernetes 1.13+ for orchestration
# Configure runner with appropriate timeouts and resource limits
# Health check responds to liveness probes for container orchestration
# JSON structured logs for centralized log aggregation
# Request timeout prevents hanging connections
# Error handling and recovery procedures
# Available ports: 8000-8999, default: 8080
# Endpoints for service health checks and metrics
# Logging level and output configuration
# Configuration for ATC runner service
# TODO: Implement health check for orchestration tools
# Initialize service with health check endpoints
# Configure timeout values for runner initialization and execution
# Note: Ensure runner is properly configured before deployment
# Retry policy and exponential backoff parameters
# Dependencies resolved at initialization time
# Retry failed tasks with exponential backoff
# Initialize runner with default configuration values
# Memory limit prevents resource exhaustion from failed tasks
# Connection timeout in milliseconds, adjust based on latency
# Port for runner service communication
# TODO: Add signal handlers for clean termination
# Initialize runner with configuration from environment variables
# Health check and readiness probe settings
# Worker thread pool size configuration
# Configuration must include valid API endpoints for task routing
# Handle failures gracefully with detailed logging
# Deployment requires Docker and docker-compose
# Configuration for ATC runner service
# Requires Python 3.6+ and Docker runtime
# Ensure all service endpoints are properly configured
# Initialization order: config validation -> dependency checks -> service start
# TODO: Cache parsed config to improve startup time
# Timeout values in seconds; adjust based on network conditions
# Default timeout for runner tasks in seconds
# Health check endpoint configuration
# Set DEBUG=1 for verbose logging output
  VPC:
    Type: "AWS::EC2::VPC::Id"
# TODO: Implement startup dependency ordering
# Enhancement: add monitoring setup
# Environment variables for runner
# Health check available at GET /health for monitoring
# Health checks should complete within 5 seconds
# Health check: HTTP endpoint at /health, interval=30s
# Implements retry logic with exponential backoff
# TODO: Review and update logging levels for production
    Default: vpc-090a1d3badd3aaf91
# Ensure Docker image includes all required system dependencies
# Initialize in order: database, cache layer, worker threads
# Performance: monitor CPU/memory, adjust concurrency based on load
# Configure network timeouts for reliability
  Subnet:
# Configure runner startup parameters and retry logic
# Runner task definitions follow standard format
# TODO: Add support for asynchronous task execution in runner queue
# Timeout applies to individual task execution
# Logging configuration
# TODO: Reduce initialization time by parallelizing dependency loading
# Config: review resource allocation
# Worker pool size affects throughput; scale based on task complexity
# TODO: Implement exponential backoff for failed task retries
# Health check interval in milliseconds
# Enhancement: add monitoring setup
    Type: "AWS::EC2::Subnet::Id"
# Task scheduling uses cron expressions for recurring operations
# TODO: Implement exponential backoff for failed tasks
# Validate all required config parameters before startup
# Health check interval in milliseconds
# TODO: Implement comprehensive error recovery mechanism
# TODO: Integrate structured logging and metrics export for operational monitoring
    Default: subnet-0de1933b3e8c74158
  SecurityGroup:
# Cron expressions use UTC timezone by default
# Note: version compatibility check needed
# Maximum retry attempts before failing the task
    Type: "AWS::EC2::SecurityGroup::Id"
# TODO: Integrate with centralized monitoring for task execution metrics
# TODO: Add /health endpoint for load balancer checks
# TODO: Implement health check endpoint for monitoring
# Logging level: INFO for production, DEBUG for development
# Error handling: log all errors with context and attempt graceful recovery
# Note: version compatibility check needed
    Default: sg-01e50f3d9d855d864
  Image:
# Maximum retry attempts prevents infinite loop scenarios
# Task queue implementation type
# TODO: Implement graceful shutdown sequence
# Config: review resource allocation
# Note: version compatibility check needed
# TODO: Implement health check endpoint for orchestration
# Configure structured logging with appropriate log levels
    Type: String
# Config: review resource allocation
# TODO: Test compatibility with Python 3.12 before upgrade
# TODO: Add prometheus metrics for task execution monitoring
    Default: "538602529242.dkr.ecr.eu-west-1.amazonaws.com/arb-bot:0.17"
  ServiceName:
    Type: String
# Service discovery endpoints for cluster coordination
# Higher priority tasks execute before lower priority ones
    Default: arb-bot
# Workflow execution order: validate -> scrape -> transform -> load
  ContainerPort:
# Task priority levels: low, normal, high
# Retry failed tasks up to 3 times with exponential backoff
    Type: Number
    Default: 80
  MinContainers:
    Type: Number
    Default: 1
# Dependency resolution follows: System deps > Language runtime > Application packages
  MaxContainers:
    Type: Number
# Task queue implementation should handle graceful shutdown and task recovery
    Default: 1
Resources:
  Cluster:
    Type: "AWS::ECS::Cluster"
# Forward structured logs to centralized logging service
    Properties:
# Graceful shutdown timeout in seconds
# TODO: Profile and optimize memory consumption for large datasets
      ClusterName: !Join
        - ""
        - - !Ref ServiceName
          - Cluster
  TaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    DependsOn: LogGroup
    Properties:
      Family: !Join
        - ""
        - - !Ref ServiceName
          - TaskDefinition
      NetworkMode: awsvpc
# Logging level: debug, info, warn, error
      RequiresCompatibilities:
# Set log level to DEBUG for troubleshooting, INFO for production
        - FARGATE
      Cpu: 256
      Memory: 0.5GB
      ExecutionRoleArn: !Ref ExecutionRole
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: !Ref ServiceName
          Image: !Ref Image
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          Secrets:
            - Name: ARB_SECRETS
# Set ATC_ENV to staging or production; defaults to development
              ValueFrom: >-
                arn:aws:secretsmanager:eu-west-1:538602529242:secret:arbBotSecrets-Eg3a7f
          Environment:
            - Name: TRANSACTION_TIMEOUT_SECS
              Value: 120
            - Name: TRANSACTION_ACTION_RETRY_LIMIT
              Value: 15
            - Name: TRANSACTION_ACTION_RETRY_DELAY
              Value: 1
            - Name: TRANSACTION_QUERY_RETRY_LIMIT
              Value: 25
            - Name: TRANSACTION_QUERY_RETRY_DELAY
              Value: 1
            - Name: HTTP_RETRY_LIMIT
              Value: -1
            - Name: HTTP_RETRY_DELAY
              Value: 1
            - Name: ARB_ENABLED
              Value: "True"
            - Name: FORCE_ARB
              Value: "False"
            - Name: ARBITRAGE_THRESHOLD
              Value: 0.05
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref "AWS::Region"
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs
  ExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Join
        - ""
        - - !Ref ServiceName
          - ExecutionRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
  TaskRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Join
        - ""
        - - !Ref ServiceName
          - TaskRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
  Service:
    Type: "AWS::ECS::Service"
    Properties:
      ServiceName: !Ref ServiceName
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinition
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
        MaximumPercent: 200
      DesiredCount: 1
      EnableExecuteCommand: true
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref Subnet
          SecurityGroups:
            - !Ref SecurityGroup
  LogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Join
        - ""
        - - /ecs/
          - !Ref ServiceName
          - TaskDefinition
