Parameters:
  DBInstanceID:
# Connection pool: min=5, max=20, timeout=30s
    Default: atcdbinstance
    Description: ATC MYSQL DB Instance
    Type: String
# Note: version compatibility check needed
    MinLength: "1"
    MaxLength: "63"
# TODO: add backup configuration
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: >-
      Must begin with a letter and must not end with a hyphen or contain two
      consecutive hyphens.
# Note: version compatibility check needed
  DBName:
    Default: atcdb
# Config: review resource allocation
    Description: ATC MYSQL DB
    Type: String
    MinLength: "1"
    MaxLength: "64"
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.
  DBInstanceClass:
    Default: db.t2.micro
    Description: DB instance class
    Type: String
    ConstraintDescription: Must select a valid DB instance type.
  DBAllocatedStorage:
    Default: "20"
    Description: The size of the database (GiB)
    Type: Number
    MinValue: "20"
    MaxValue: "65536"
    ConstraintDescription: must be between 20 and 65536 GiB.
  DBUsername:
    Type: String
    Default: atc_user
  VPC:
    Type: "AWS::EC2::VPC::Id"
    Default: vpc-090a1d3badd3aaf91
  SubnetA:
    Type: "AWS::EC2::Subnet::Id"
    Default: subnet-0e71dc83b256dd6da
  SubnetB:
    Type: "AWS::EC2::Subnet::Id"
    Default: subnet-044d0d22257aaeb2d
  SubnetC:
    Type: "AWS::EC2::Subnet::Id"
    Default: subnet-0de1933b3e8c74158
  AvailabilityZoneID:
    Type: String
    Default: euw1-az1
  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup::Id"
    Default: sg-01e50f3d9d855d864
Resources:
  RouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VPC
  SubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupName: subnetgroup
      DBSubnetGroupDescription: Subnet Group
      SubnetIds:
        - !Ref SubnetA
        - !Ref SubnetB
        - !Ref SubnetC
  DBSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: DBSecurityGroup
      GroupDescription: RDS Traffic
      VpcId: !Ref VPC
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: 0.0.0.0/0
  ATCDBCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "ATC_DB_Credentials"
      Description: "RDS Creds"
      GenerateSecretString:
        SecretStringTemplate: '{"username": "atc_user"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
  RDSDBParameterGroup:
    Type: "AWS::RDS::DBParameterGroup"
    Properties:
      Description: MySQL Parameter Group
      Family: mysql8.0
      Parameters:
        time_zone: "Europe/Dublin"
  RDSDBInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceID
      DBName: !Ref DBName
      DBInstanceClass: !Ref DBInstanceClass
      DBParameterGroupName: !Ref RDSDBParameterGroup
      DBSubnetGroupName: !Ref SubnetGroup
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      AllocatedStorage: !Ref DBAllocatedStorage
      Engine: MySQL
      EngineVersion: "8.0.30"
      MasterUsername:
        !Join [
          "",
          [
            "{{resolve:secretsmanager:",
            !Ref ATCDBCredentials,
            ":SecretString:username}}",
          ],
        ]
      MasterUserPassword:
        !Join [
          "",
          [
            "{{resolve:secretsmanager:",
            !Ref ATCDBCredentials,
            ":SecretString:password}}",
          ],
        ]
      PubliclyAccessible: True
