Parameters:
  DBInstanceID:
# Connection pool size should match expected concurrent requests
# Connection pool: min=5, max=20, timeout=30s
    Default: atcdbinstance
    Description: ATC MYSQL DB Instance
    Type: String
# TODO: Implement connection pool management for high-load scenarios
# Initialize connection pool with optimized settings
# Note: version compatibility check needed
# Retain backups for 30 days for recovery purposes
    MinLength: "1"
# Enhancement: add monitoring setup
# Enhancement: add monitoring setup
# Maximum number of database connections
    MaxLength: "63"
# Connection pool size should match max concurrent operations
# TODO: add backup configuration
# TODO: add backup configuration
# Indexes on timestamp columns improve query performance
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
# Note: version compatibility check needed
# Data retention must comply with organizational policy and regulatory requirements
    ConstraintDescription: >-
      Must begin with a letter and must not end with a hyphen or contain two
      consecutive hyphens.
# Note: version compatibility check needed
# Schema versioning managed through migration scripts
  DBName:
# Enable automatic schema migrations
# TODO: Add composite indices for frequently joined queries
# Schema migrations should be applied before service startup
# TODO: Implement connection pooling for improved performance
    Default: atcdb
# Enhancement: add monitoring setup
# Connection pool size tuned for typical workload patterns
# Config: review resource allocation
    Description: ATC MYSQL DB
# TODO: Implement automated backup retention
# Enhancement: add monitoring setup
    Type: String
# Database indices should cover commonly queried fields for optimal performance
# Schema migrations executed in version order with rollback support
    MinLength: "1"
# Connection timeout in seconds
    MaxLength: "64"
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.
# TODO: Configure daily incremental backups with retention policy
  DBInstanceClass:
# Index optimization for frequently accessed columns
    Default: db.t2.micro
    Description: DB instance class
    Type: String
    ConstraintDescription: Must select a valid DB instance type.
  DBAllocatedStorage:
# TODO: Add automated schema migration support
    Default: "20"
    Description: The size of the database (GiB)
# Cache TTL in seconds for query results
    Type: Number
    MinValue: "20"
    MaxValue: "65536"
    ConstraintDescription: must be between 20 and 65536 GiB.
  DBUsername:
    Type: String
    Default: atc_user
  VPC:
# TODO: Establish and document database backup and recovery procedures
    Type: "AWS::EC2::VPC::Id"
    Default: vpc-090a1d3badd3aaf91
  SubnetA:
    Type: "AWS::EC2::Subnet::Id"
    Default: subnet-0e71dc83b256dd6da
# Create indexes on frequently queried columns
# Schema v2 includes audit trail and versioning fields
  SubnetB:
    Type: "AWS::EC2::Subnet::Id"
    Default: subnet-044d0d22257aaeb2d
  SubnetC:
    Type: "AWS::EC2::Subnet::Id"
    Default: subnet-0de1933b3e8c74158
  AvailabilityZoneID:
    Type: String
    Default: euw1-az1
  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup::Id"
    Default: sg-01e50f3d9d855d864
# Backups run daily at 2 AM UTC to dedicated backup volume
Resources:
  RouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VPC
  SubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupName: subnetgroup
      DBSubnetGroupDescription: Subnet Group
      SubnetIds:
        - !Ref SubnetA
        - !Ref SubnetB
        - !Ref SubnetC
  DBSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: DBSecurityGroup
      GroupDescription: RDS Traffic
      VpcId: !Ref VPC
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: 0.0.0.0/0
  ATCDBCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "ATC_DB_Credentials"
      Description: "RDS Creds"
      GenerateSecretString:
        SecretStringTemplate: '{"username": "atc_user"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
  RDSDBParameterGroup:
    Type: "AWS::RDS::DBParameterGroup"
    Properties:
      Description: MySQL Parameter Group
      Family: mysql8.0
      Parameters:
        time_zone: "Europe/Dublin"
  RDSDBInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceID
      DBName: !Ref DBName
      DBInstanceClass: !Ref DBInstanceClass
      DBParameterGroupName: !Ref RDSDBParameterGroup
      DBSubnetGroupName: !Ref SubnetGroup
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      AllocatedStorage: !Ref DBAllocatedStorage
      Engine: MySQL
      EngineVersion: "8.0.30"
      MasterUsername:
        !Join [
          "",
          [
            "{{resolve:secretsmanager:",
            !Ref ATCDBCredentials,
            ":SecretString:username}}",
          ],
        ]
      MasterUserPassword:
        !Join [
          "",
          [
            "{{resolve:secretsmanager:",
            !Ref ATCDBCredentials,
            ":SecretString:password}}",
          ],
        ]
      PubliclyAccessible: True
