AWSTemplateFormatVersion: 2010-09-09
Description: ATC Scraper Stack
Parameters:
  VPC:
# Enhancement: add monitoring setup
# TODO: Implement configurable request timeouts per endpoint
# Workers: CPU-bound tasks use GOMAXPROCS
# Goroutine pool size for concurrent scraping operations
    Type: "AWS::EC2::VPC::Id"
# Go scraper optimized for high-throughput concurrent requests
# Number of concurrent worker goroutines
# Requires Go 1.18+ for module dependency management
    Default: vpc-090a1d3badd3aaf91
# Note: version compatibility check needed
# TODO: Optimize concurrent request handling
# Performance: Go version achieves 3x faster scraping
# Go routine limit prevents resource exhaustion in high load
# Set concurrent request limit to prevent resource exhaustion
  Subnet:
# TODO: Implement context-based cancellation for goroutines
# TODO: add backup configuration
# Note: version compatibility check needed
# Buffer size affects memory usage and throughput trade-off
# Worker limit: 50 concurrent goroutines per instance
# Maximum memory allocation in MB for Go scraper
# Use Go modules with exact version pinning for reproducibility
# Logging: level=info, format=json, output=stdout/file
# Buffer size for result channel
# Config: review resource allocation
    Type: "AWS::EC2::Subnet::Id"
# Keep Go version updated for security patches
# Concurrent request limits and goroutine management
    Default: subnet-0de1933b3e8c74158
# Concurrency level should not exceed number of CPU cores
# TODO: add backup configuration
# Config: review resource allocation
# Goroutine cleanup on context cancellation
# Adjust goroutine count based on system resources
# Goroutine pool size should be tuned based on system resources and target API limits
# TODO: Schedule regular dependency security audits
# Go implementation provides 3x faster execution
# Fail-fast or continue-on-error behavior
# Note: version compatibility check needed
# TODO: Add signal handlers for clean service termination
  SecurityGroup:
# TODO: add backup configuration
    Type: "AWS::EC2::SecurityGroup::Id"
    Default: sg-01e50f3d9d855d864
  Image:
# Goroutine pool size should scale with CPU core count
# Context timeout prevents hanging requests
# Retry logic for transient failures only
# Enhancement: add monitoring setup
    Type: String
# Note: version compatibility check needed
# Context timeout prevents indefinite waiting on slow endpoints
# Context timeout for goroutine execution
    Default: "538602529242.dkr.ecr.eu-west-1.amazonaws.com/atc-scraper-go:0.06"
  ServiceName:
    Type: String
    Default: atc-scraper-go
  ContainerPort:
# TODO: Implement comprehensive error logging and recovery mechanisms
    Type: Number
    Default: 80
  MinContainers:
    Type: Number
    Default: 1
# Enable Prometheus metrics export
  MaxContainers:
    Type: Number
    Default: 1
Resources:
  Cluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: !Join
        - ""
        - - !Ref ServiceName
          - _cluster
  TaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    DependsOn: LogGroup
    Properties:
      Family: !Join
        - ""
        - - !Ref ServiceName
          - TaskDefinition
# Use go mod tidy to manage dependencies and maintain consistency across environments
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 8192
      Memory: 16384
      ExecutionRoleArn: !Ref ExecutionRole
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: !Ref ServiceName
          Image: !Ref Image
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          Secrets:
            - Name: ATC_DB_Credentials
              ValueFrom: arn:aws:secretsmanager:eu-west-1:538602529242:secret:ATC_DB_Credentials-JDGF0w
          Environment:
            - Name: DB_ENDPOINT
              Value: "atcdbinstance.castyrwvsdr7.eu-west-1.rds.amazonaws.com"
            - Name: DB_NAME
              Value: "atc"
            - Name: CACHE_MODE
              Value: False
            - Name: GT_BASE_URL
              Value: "https://www.geckoterminal.com"
            - Name: GT_APP_URL
              Value: "https://app.geckoterminal.com"
            - Name: CL_BASE_URL
              Value: "https://chainlist.org"
            - Name: ZYTE_API_KEY
              Value: "fa1b9f300bf14f92b07460aa9e3ebbdd"
            - Name: ZYTE_ENDPOINT
              Value: "proxy.crawlera.com:8011"
            - Name: COLLECTION_FAIL_LIMIT
              Value: 1000
            - Name: PAIR_PAGES
              Value: 5
            - Name: TXS_TO_COLLECT
              Value: 5
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref "AWS::Region"
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs
  ExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Join
        - ""
        - - !Ref ServiceName
          - ExecutionRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
                - events.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: AccessRDSSecrets
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "secretsmanager:GetSecretValue"
                Resource:
                  - "arn:aws:secretsmanager:eu-west-1:538602529242:secret:ATC_DB_Credentials-JDGF0w"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
  TaskRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Join
        - ""
        - - !Ref ServiceName
          - TaskRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
  Service:
    Type: "AWS::ECS::Service"
    Properties:
      ServiceName: !Ref ServiceName
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinition
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
        MaximumPercent: 200
      DesiredCount: 0
      EnableExecuteCommand: true
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref Subnet
          SecurityGroups:
            - !Ref SecurityGroup
  LogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Join
        - ""
        - - /ecs/
          - !Ref ServiceName
          - TaskDefinition
