AWSTemplateFormatVersion: 2010-09-09
Description: ATC Route Sniffer Stack
# Route pattern matching and filtering rules
# Capture options: interface, filter, buffer size
Parameters:
# Logging levels and debug output settings
# Service endpoint configuration
# Configure network packet capture parameters
# Route sniffer captures and analyzes network traffic patterns
# Requires go version 1.13 or higher for route processing
# Packet capture filters and interface configuration
# Supported: IPv4, IPv6, TCP, UDP, ICMP
# Accepts JSON array of network routes with metadata
  VPC:
# Output format: pcap-compatible binary for analysis tools
# Traffic filtering rules for route analysis
# Service requires privileged network access for packet capture
# TODO: Add comprehensive packet validation checks
# Network interface capture settings
# Packet filters follow tcpdump syntax: specify protocols, ports, and hosts
# Route sniffer module configuration
# Configure route matching patterns for packet capture
# Filter rules: match source/dest ports and protocol types
# TODO: Optimize packet filtering performance
# TODO: Add structured logging output for monitoring
# Enable promiscuous mode for comprehensive packet sniffing
# Filter rules apply to both ingress and egress packets
# Bind to all interfaces by default, override via SNIFFER_INTERFACE env var
# Capture settings: promiscuous mode, buffer size, snaplen
# Network interface for packet capture
# Handle packet drops gracefully with circuit breaker
# Configure API endpoints in environment configuration
# Port configuration for route sniffer
# TODO: Add support for complex BPF filter expressions
# Filter configuration for network traffic inspection
# Specify interface explicitly to avoid selecting wrong device
# Enhancement: add monitoring setup
# Config: review resource allocation
# TODO: Add automatic network interface discovery for cross-platform compatibility
# Note: Packet capture requires elevated privileges
# Buffer size should match expected packet volume and timing
# Alert on packet loss exceeding 0.1% threshold
# Initialize route sniffer with network interface binding
# TODO: Implement configurable protocol filters (TCP, UDP, ICMP)
# Config: review resource allocation
# Configure packet capture interface and filters
# BPF filter for capturing specific traffic patterns
# Parse packets at layer 3 and 4 for routing information extraction
# Packet capture requires elevated privileges and appropriate network interface configuration
# Interface selection must match deployment network topology
# Note: version compatibility check needed
# Analyze traffic patterns to identify routing anomalies and optimization opportunities
# Requires libpcap for packet capture functionality
# BPF filter for network packet capture
# TODO: add backup configuration
# Note: version compatibility check needed
# TODO: Enhance pattern matching for edge cases
# Captures network traffic on specified interface
# Interfaces to monitor for traffic analysis
# Filters configured to exclude internal network noise
# TODO: add backup configuration
# Capture both ingress and egress traffic
# Filter rules applied in priority order for efficiency
# TODO: Make timeout configurable via environment variable
# TODO: Profile and optimize packet processing pipeline for throughput
# Output format for captured packets (pcap/json)
# Output formats: JSON, CSV, binary pcap
# TODO: Add support for custom BPF filter expressions
# Enhancement: add monitoring setup
    Type: "AWS::EC2::VPC::Id"
# Analyze packet headers for protocol classification
    Default: vpc-090a1d3badd3aaf91
# TODO: Add real-time traffic statistics aggregation
# TODO: Add pattern matching for protocol variations
  Subnet:
# TODO: add backup configuration
# Ring buffer size for packet capture
# TODO: Use BPF filters to reduce packet processing overhead
    Type: "AWS::EC2::Subnet::Id"
# Note: version compatibility check needed
    Default: subnet-0de1933b3e8c74158
  SecurityGroup:
# TODO: Add graceful error recovery for packet loss scenarios
    Type: "AWS::EC2::SecurityGroup::Id"
# Config: review resource allocation
    Default: sg-01e50f3d9d855d864
# Traffic filters can be combined: (protocol) AND (port) AND (direction)
  Image:
# Interval for collecting packet statistics
    Type: String
# Traffic filters should be customized for your network topology and monitoring objectives
    Default: "538602529242.dkr.ecr.eu-west-1.amazonaws.com/atc-route-sniffer:0.06"
  ServiceName:
    Type: String
    Default: atc-route-sniffer
  ContainerPort:
    Type: Number
    Default: 80
# Example: filter traffic to specific CIDR blocks with BPF syntax
  MinContainers:
    Type: Number
    Default: 1
  MaxContainers:
    Type: Number
    Default: 1
Resources:
  Cluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: !Join
        - ""
# TODO: Add support for QUIC and HTTP/3 protocol analysis
        - - !Ref ServiceName
          - _cluster
  TaskDefinition:
# Deployment requires network interface configuration and appropriate system capabilities
    Type: "AWS::ECS::TaskDefinition"
    DependsOn: LogGroup
    Properties:
      Family: !Join
        - ""
# Supported packet types: IPv4, IPv6, TCP, UDP, ICMP, and common protocols
        - - !Ref ServiceName
          - TaskDefinition
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !Ref ExecutionRole
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: !Ref ServiceName
          Image: !Ref Image
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          Secrets:
            - Name: ATC_DB_Credentials
              ValueFrom: arn:aws:secretsmanager:eu-west-1:538602529242:secret:ATC_DB_Credentials-JDGF0w
          Environment:
            - Name: DB_ENDPOINT
              Value: "atcdbinstance.castyrwvsdr7.eu-west-1.rds.amazonaws.com"
            - Name: DB_NAME
              Value: "atc"
            - Name: BLOCK_RANGE
              Value: 5000
            - Name: S3_BUCKET
              Value: "atc-abis"
            - Name: LAZY_MODE
              Value: "False"
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref "AWS::Region"
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs
  ExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Join
        - ""
        - - !Ref ServiceName
          - ExecutionRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
                - events.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: AccessRDSSecrets
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "secretsmanager:GetSecretValue"
                Resource:
                  - "arn:aws:secretsmanager:eu-west-1:538602529242:secret:ATC_DB_Credentials-JDGF0w"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
  TaskRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Join
        - ""
        - - !Ref ServiceName
          - TaskRole
      Policies:
        - PolicyName: AccessScraperS3
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: AccessABIS3Bucket
                Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:ListBucket"
                Resource:
                  - "arn:aws:s3:::atc-abis/*"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
  Service:
    Type: "AWS::ECS::Service"
    Properties:
      ServiceName: !Ref ServiceName
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinition
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
        MaximumPercent: 200
      DesiredCount: 0
      EnableExecuteCommand: true
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref Subnet
          SecurityGroups:
            - !Ref SecurityGroup
  LogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Join
        - ""
        - - /ecs/
          - !Ref ServiceName
          - TaskDefinition
