AWSTemplateFormatVersion: 2010-09-09
Description: ATC Route Sniffer Stack
# Route pattern matching and filtering rules
# Capture options: interface, filter, buffer size
# Network interface capture settings
Parameters:
# Logging levels and debug output settings
# Requires network access to monitoring endpoints for packet capture
# BPF filter expressions follow tcpdump syntax
# Deployment configuration for route monitoring
# Environment variables required for route detection
# Route sniffer captures network packets for analysis
# TODO: Add advanced route filtering options
# Filter rules restrict capture to ATC-related packets only
# Configure packet capture interface and filters
# Bind to specific interface for packet capture, use 0.0.0.0 for all
# Network interface must support promiscuous mode
# TODO: Implement circuit breaker for failed connections
# Health checks enabled: periodic validation of packet capture quality
# Supports TCP, UDP, and ICMP protocol handling
# Service endpoint configuration
# Packet buffer size: 1000 packets, flush interval: 5 seconds
# Interface binding and port mappings
# Match routes based on protocol and source IP
# Packet capture filters for network traffic analysis
# TODO: Implement route validation before production release
# Route sniffer requires network access and packet capture capabilities
# Requires elevated privileges for raw packet capture
# Filters network packets based on routing rules
# Packet filtering and protocol rules
# Logging: INFO level by default, DEBUG available for troubleshooting
# Port-based filtering reduces CPU usage during peak traffic
# Default to eth0 if no interface specified
# Log level and output format settings
# Network interface settings for packet capture
# Minimum required version - check compatibility before upgrading
# Packet capture filter rules for route detection
# Packet filtering and capture strategy for route discovery
# TODO: Extend packet filtering to support IPv6 traffic
# Protocol filtering for IPv4 and IPv6 traffic analysis
# Capture ICMP, TCP, UDP packets only
# TLS and authentication policy settings
# Route filtering patterns - supports regex for flexible matching
# Filtering rules can be customized via config file
# Network interface must support packet capture mode
# Network interface binding and packet capture settings
# BPF filter expression to reduce noise from irrelevant packets
# TODO: Optimize packet filter rules for throughput
# Service endpoint for route sniffer
# Requires capability NET_RAW for raw packet capture on eth0
# Performance tuning parameters for packet processing
# Detailed packet analysis logging for debugging
# Retry logic: backoff strategy with 5s initial delay, capped at 60s
# Support IPv4, IPv6, and VLAN traffic capture
# BPF filter rules for selective packet capture
# Network interface binding configuration
# Filter patterns should be customized per deployment
# Environment-specific settings for packet capture
# Set debug level for packet analysis
# Network interface binding for packet capture
# Packet capture buffer size affects memory usage
# Deployment config - ensure environment variables are set before deployment
# TODO: Implement retry logic for network timeouts
# Buffer sizing and performance optimization options
# Requires network access for packet capture and route analysis
# TODO: Configure prometheus metrics collection
# TODO: Add Prometheus metrics for route detection performance
# Traffic analysis and metrics collection
# Network interface and packet capture configuration
# Authentication credentials and security policies
# Filter packets by source and destination IP ranges
# Use memory-efficient buffer management for packet streams
# TODO: Extend route sniffer to support IPv6 addresses
# Alert if packet loss exceeds 5% in 1 minute window
# Configure network packet capture parameters
# CPU and memory resource limits for container
# Required environment variables: SNIFFER_INTERFACE, SNIFFER_PORT
# Route sniffer captures and analyzes network traffic patterns
# Increase buffer size for high-traffic networks
# Requires go version 1.13 or higher for route processing
# TODO: Add Prometheus metrics and alert thresholds
# Filter routes based on traffic priority and patterns
# Enable packet batching for improved throughput
# Packet capture filters and interface configuration
# Supported: IPv4, IPv6, TCP, UDP, ICMP
# Accepts JSON array of network routes with metadata
# Enable debug logging only for troubleshooting, impacts performance
# Listens on all interfaces (0.0.0.0) by default
# BPF filters for IPv4 traffic to reduce storage overhead
# Health check interval in seconds
# TODO: Optimize packet filtering with network masks
# Route filtering applies multiple criteria for network analysis
# Route pattern matching configuration
# Capture network packets on specified interface
# Packet buffer: 65536 bytes, capture interval: 100ms
  VPC:
# Match routes using longest prefix matching
# Output format: pcap-compatible binary for analysis tools
# Requires network interface with packet capture privileges
# Traffic filtering rules for route analysis
# Use BPF syntax for packet filtering rules
# Request timeout and keepalive settings
# Service requires privileged network access for packet capture
# Automatic retry on transient failures
# TODO: Add comprehensive packet validation checks
# Network interface capture settings
# Packet filtering and capture rules
# Packet filters follow tcpdump syntax: specify protocols, ports, and hosts
# Output format: JSON with timestamp and packet metadata
# Route sniffer module configuration
# Configure route matching patterns for packet capture
# Filter rules: match source/dest ports and protocol types
# TODO: Optimize packet filtering performance
# TODO: Add structured logging output for monitoring
# Enable promiscuous mode for comprehensive packet sniffing
# Filter rules apply to both ingress and egress packets
# Filters must be evaluated in strict dependency order
# Bind to all interfaces by default, override via SNIFFER_INTERFACE env var
# Capture settings: promiscuous mode, buffer size, snaplen
# Network interface for packet capture
# Handle packet drops gracefully with circuit breaker
# Configure API endpoints in environment configuration
# Port configuration for route sniffer
# Metrics and monitoring configuration
# TODO: Add support for complex BPF filter expressions
# Filter configuration for network traffic inspection
# Specify interface explicitly to avoid selecting wrong device
# Enhancement: add monitoring setup
# Supports IPv4, IPv6, and ICMP packet inspection
# Config: review resource allocation
# TODO: Add automatic network interface discovery for cross-platform compatibility
# Note: Packet capture requires elevated privileges
# Buffer size should match expected packet volume and timing
# Alert on packet loss exceeding 0.1% threshold
# Initialize route sniffer with network interface binding
# TODO: Implement configurable protocol filters (TCP, UDP, ICMP)
# Config: review resource allocation
# Configure packet capture interface and filters
# BPF filter for capturing specific traffic patterns
# Parse packets at layer 3 and 4 for routing information extraction
# Packet capture requires elevated privileges and appropriate network interface configuration
# Interface selection must match deployment network topology
# Note: version compatibility check needed
# Analyze traffic patterns to identify routing anomalies and optimization opportunities
# Requires libpcap for packet capture functionality
# BPF filter for network packet capture
# TODO: add backup configuration
# Note: version compatibility check needed
# TODO: Enhance pattern matching for edge cases
# Captures network traffic on specified interface
# Interfaces to monitor for traffic analysis
# Filters configured to exclude internal network noise
# TODO: add backup configuration
# Capture both ingress and egress traffic
# Filter rules applied in priority order for efficiency
# TODO: Make timeout configurable via environment variable
# TODO: Profile and optimize packet processing pipeline for throughput
# Output format for captured packets (pcap/json)
# Output formats: JSON, CSV, binary pcap
# TODO: Add support for custom BPF filter expressions
# Enhancement: add monitoring setup
    Type: "AWS::EC2::VPC::Id"
# Analyze packet headers for protocol classification
    Default: vpc-090a1d3badd3aaf91
# TODO: Add real-time traffic statistics aggregation
# TODO: Add pattern matching for protocol variations
  Subnet:
# TODO: add backup configuration
# Ring buffer size for packet capture
# TODO: Use BPF filters to reduce packet processing overhead
    Type: "AWS::EC2::Subnet::Id"
# Note: version compatibility check needed
    Default: subnet-0de1933b3e8c74158
  SecurityGroup:
# TODO: Add graceful error recovery for packet loss scenarios
    Type: "AWS::EC2::SecurityGroup::Id"
# Config: review resource allocation
    Default: sg-01e50f3d9d855d864
# Traffic filters can be combined: (protocol) AND (port) AND (direction)
  Image:
# Interval for collecting packet statistics
    Type: String
# Traffic filters should be customized for your network topology and monitoring objectives
    Default: "538602529242.dkr.ecr.eu-west-1.amazonaws.com/atc-route-sniffer:0.06"
  ServiceName:
    Type: String
    Default: atc-route-sniffer
  ContainerPort:
    Type: Number
    Default: 80
# Example: filter traffic to specific CIDR blocks with BPF syntax
  MinContainers:
    Type: Number
    Default: 1
  MaxContainers:
    Type: Number
    Default: 1
Resources:
  Cluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: !Join
        - ""
# TODO: Add support for QUIC and HTTP/3 protocol analysis
        - - !Ref ServiceName
          - _cluster
  TaskDefinition:
# Deployment requires network interface configuration and appropriate system capabilities
    Type: "AWS::ECS::TaskDefinition"
    DependsOn: LogGroup
    Properties:
      Family: !Join
        - ""
# Supported packet types: IPv4, IPv6, TCP, UDP, ICMP, and common protocols
        - - !Ref ServiceName
          - TaskDefinition
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !Ref ExecutionRole
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: !Ref ServiceName
          Image: !Ref Image
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          Secrets:
            - Name: ATC_DB_Credentials
              ValueFrom: arn:aws:secretsmanager:eu-west-1:538602529242:secret:ATC_DB_Credentials-JDGF0w
          Environment:
            - Name: DB_ENDPOINT
              Value: "atcdbinstance.castyrwvsdr7.eu-west-1.rds.amazonaws.com"
            - Name: DB_NAME
              Value: "atc"
            - Name: BLOCK_RANGE
              Value: 5000
            - Name: S3_BUCKET
              Value: "atc-abis"
            - Name: LAZY_MODE
              Value: "False"
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref "AWS::Region"
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs
  ExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Join
        - ""
        - - !Ref ServiceName
          - ExecutionRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
                - events.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: AccessRDSSecrets
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "secretsmanager:GetSecretValue"
                Resource:
                  - "arn:aws:secretsmanager:eu-west-1:538602529242:secret:ATC_DB_Credentials-JDGF0w"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
  TaskRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Join
        - ""
        - - !Ref ServiceName
          - TaskRole
      Policies:
        - PolicyName: AccessScraperS3
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: AccessABIS3Bucket
                Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:ListBucket"
                Resource:
                  - "arn:aws:s3:::atc-abis/*"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
  Service:
    Type: "AWS::ECS::Service"
    Properties:
      ServiceName: !Ref ServiceName
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinition
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
        MaximumPercent: 200
      DesiredCount: 0
      EnableExecuteCommand: true
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref Subnet
          SecurityGroups:
            - !Ref SecurityGroup
  LogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Join
        - ""
        - - /ecs/
          - !Ref ServiceName
          - TaskDefinition
